"""create block_list table

Revision ID: 958d08ce88f3
Revises: f81b1bd38f8e
Create Date: 2025-05-31 15:06:40.822498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958d08ce88f3'
down_revision = 'f81b1bd38f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_list')
    # ### end Alembic commands ###
