"""add user_role in docto_info table

Revision ID: d688e9f2c176
Revises: d7f6014717c3
Create Date: 2025-06-01 20:25:27.126645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd688e9f2c176'
down_revision = 'd7f6014717c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_information', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
