"""added doctor table and added relationships

Revision ID: d7f6014717c3
Revises: 958d08ce88f3
Create Date: 2025-06-01 20:03:40.491854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f6014717c3'
down_revision = '958d08ce88f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_information',
    sa.Column('doctor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('doctor_email', sa.String(length=150), nullable=False),
    sa.Column('doctor_password', sa.String(length=255), nullable=False),
    sa.Column('doctor_active', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_information.store_id'], ),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('doctor_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_information')
    # ### end Alembic commands ###
