"""Added email field to User model

Revision ID: e05956d7472c
Revises: 
Create Date: 2025-05-29 00:04:08.557746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e05956d7472c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_information', schema=None) as batch_op:
        batch_op.alter_column('store_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('store_landmark',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('store_city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('store_state',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('store_owner',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('store_zip_code',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('store_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_password',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('user_city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_state',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_information', schema=None) as batch_op:
        batch_op.alter_column('user_role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('user_state',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_password',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('email')

    with op.batch_alter_table('store_information', schema=None) as batch_op:
        batch_op.alter_column('store_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('store_zip_code',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('store_owner',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('store_state',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('store_city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('store_landmark',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('store_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
