"""Initial DB schema

Revision ID: e2a402757e3d
Revises: 
Create Date: 2025-06-02 13:39:55.701026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a402757e3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_information', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doctor_store'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'store_information', ['store_id'], ['store_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_information', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_doctor_store'), 'store_information', ['store_id'], ['store_id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###
